# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
