# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0002_mp_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='profile',
            field=models.TextField(null=True),
        ),
    ]
