# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intro',
            field=models.TextField(null=True),
        ),
    ]
